In [ ]:
import pandas as pd
import numpy as np

In [5]:
# Load the dataset using a comma as the delimiter
df = pd.read_csv('/content/marketing_campaign_performance_10000.csv', delimiter=',')

# Display the first 10 rows
display(df.head(10))

# Check the dataset dimensions
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

,CampaignID,StartDate,EndDate,Channel,Impressions,Clicks,Leads,Conversions,Cost_USD,Revenue_USD,ROI
0,CAMP00001,2025-04-13,2025-04-19,Search,293520,23335,11643,5389,1052.39,2236.02,1.12
1,CAMP00002,2025-12-15,2025-12-24,Search,200340,15841,6601,2498,3964.90,11740.15,1.96
2,CAMP00003,2025-09-28,2025-10-06,Email,239365,16478,8043,3397,1000.39,1902.24,0.90
3,CAMP00004,2025-04-17,2025-04-30,Search,156382,2672,1014,342,1252.63,2209.74,0.76
4,CAMP00005,2025-03-13,2025-03-22,Influencer,285472,4155,1521,565,4935.48,14111.31,1.86
5,CAMP00006,2025-07-08,2025-07-21,Social,177469,7979,3231,1446,3540.34,3885.94,0.10
6,CAMP00007,2025-01-21,2025-02-05,Display,174231,2160,379,107,1999.53,3306.37,0.65
7,CAMP00008,2025-04-13,2025-04-26,Display,234598,21435,9052,2295,3793.91,7159.09,0.89
8,CAMP00009,2025-05-02,2025-05-08,Influencer,209438,2474,1207,697,2385.72,2800.53,0.17
9,CAMP00010,2025-08-03,2025-08-16,Search,195376,2474,852,251,1142.07,2323.19,1.03

Number of rows: 10000
Number of columns: 11

In [4]:
df.info()
df.describe()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CampaignID   10000 non-null  object
 1   StartDate    10000 non-null  object
 2   EndDate      10000 non-null  object
 3   Channel      10000 non-null  object
 4   Impressions  10000 non-null  int64
 5   Clicks       10000 non-null  int64
 6   Leads        10000 non-null  int64
 7   Conversions  10000 non-null  int64
 8   Cost_USD     10000 non-null  float64
 9   Revenue_USD  10000 non-null  float64
 10  ROI          10000 non-null  float64
dtypes: float64(3), int64(4), object(4)
memory usage: 859.5+ KB

np.int64(0)

In [6]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
print(df.columns.tolist())

['campaignid', 'startdate', 'enddate', 'channel', 'impressions', 'clicks', 'leads', 'conversions', 'cost_usd', 'revenue_usd', 'roi']

In [7]:
# Convert 'startdate' and 'enddate' to datetime objects
df['startdate'] = pd.to_datetime(df['startdate'])
df['enddate'] = pd.to_datetime(df['enddate'])

# Display the updated data types to confirm
print("Updated DataFrame Info after datetime conversion:")
df.info()

Updated DataFrame Info after datetime conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   campaignid   10000 non-null  object
 1   startdate    10000 non-null  datetime64[ns]
 2   enddate      10000 non-null  datetime64[ns]
 3   channel      10000 non-null  object
 4   impressions  10000 non-null  int64
 5   clicks       10000 non-null  int64
 6   leads        10000 non-null  int64
 7   conversions  10000 non-null  int64
 8   cost_usd     10000 non-null  float64
 9   revenue_usd  10000 non-null  float64
 10  roi          10000 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(4), object(2)
memory usage: 859.5+ KB

In [8]:
# Convert 'channel' to a categorical data type
df['channel'] = df['channel'].astype('category')

# Display the updated data types to confirm
print("Updated DataFrame Info after category conversion:")
df.info()

Updated DataFrame Info after category conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   campaignid   10000 non-null  object
 1   startdate    10000 non-null  datetime64[ns]
 2   enddate      10000 non-null  datetime64[ns]
 3   channel      10000 non-null  category
 4   impressions  10000 non-null  int64
 5   clicks       10000 non-null  int64
 6   leads        10000 non-null  int64
 7   conversions  10000 non-null  int64
 8   cost_usd     10000 non-null  float64
 9   revenue_usd  10000 non-null  float64
 10  roi          10000 non-null  float64
dtypes: category(1), datetime64[ns](2), float64(3), int64(4), object(1)
memory usage: 791.4+ KB

In [9]:
# Check for empty strings in object/category columns
(df.select_dtypes(include=['object', 'category']) == '').sum()

campaignid    0
channel       0
dtype: int64

## Handling Missing Values

The dataset was inspected for missing values using `df.isnull().sum()`.

No missing values were found across any of the 11 columns.

Since the dataset is complete, no imputation or row removal was required. All 10,000 records were retained for subsequent analysis.

Maintaining the full dataset ensures that later calculations—such as campaign revenue, conversion rates, ROI comparisons, and channel performance—are based on complete information without introducing bias through data imputation.

In [10]:
# Check for duplicate rows
duplicate_count = df.duplicated().sum()

print(f"Number of duplicate rows: {duplicate_count}")

Number of duplicate rows: 0

## Duplicate Record Check

The dataset was examined for duplicate records using `df.duplicated().sum()`.

No duplicate rows were identified.

Since duplicate campaign records can artificially inflate marketing KPIs such as impressions, clicks, conversions, revenue, and advertising spend, verifying their absence helps ensure the accuracy of subsequent analyses.

No records were removed during this step.

In [12]:
numeric_cols = [
    'impressions',
    'clicks',
    'leads',
    'conversions',
    'cost_usd',
    'revenue_usd',
    'roi'
]

for col in numeric_cols:
    count = (df[col] < 0).sum()
    print(f"{col}: {count} negative values")

for col in numeric_cols:
    count = (df[col] == 0).sum()
    print(f"{col}: {count} zero values")

(df['clicks'] > df['impressions']).sum()

(df['leads'] > df['clicks']).sum()

(df['conversions'] > df['leads']).sum()

(df['enddate'] < df['startdate']).sum()

df['campaign_duration'] = (
    df['enddate'] - df['startdate']
).dt.days

df['campaign_duration'].describe()

(df['revenue_usd'] < df['cost_usd']).sum()

df['roi'].describe()

impressions: 0 negative values
clicks: 0 negative values
leads: 0 negative values
conversions: 0 negative values
cost_usd: 0 negative values
revenue_usd: 0 negative values
roi: 0 negative values
impressions: 0 zero values
clicks: 0 zero values
leads: 0 zero values
conversions: 0 zero values
cost_usd: 0 zero values
revenue_usd: 0 zero values
roi: 31 zero values

count    10000.000000
mean         1.001576
std          0.578806
min          0.000000
25%          0.500000
50%          0.990000
75%          1.510000
max          2.000000
Name: roi, dtype: float64

## Numerical Data Validation

The numerical variables were validated to ensure that campaign metrics were logically consistent and suitable for analysis.

The validation included:

- Checking for negative values.
- Checking for zero values.
- Verifying the marketing funnel hierarchy:
  - Impressions ≥ Clicks ≥ Leads ≥ Conversions.
- Confirming that campaign end dates occurred after campaign start dates.
- Reviewing campaign duration.
- Examining campaigns where marketing cost exceeded generated revenue.
- Inspecting the distribution of ROI values.

These validation checks help ensure that subsequent KPI calculations and campaign performance analyses are based on internally consistent data.

In [13]:
df.select_dtypes(include=['object', 'category']).columns

for col in ['campaignid', 'channel']:
    print(f"\n{col.upper()}")
    print(df[col].unique())

print(df['channel'].value_counts())

df['channel'] = (
    df['channel']
      .str.strip()
      .str.title()
)

print(df['channel'].value_counts())

CAMPAIGNID
['CAMP00001' 'CAMP00002' 'CAMP00003' ... 'CAMP09998' 'CAMP09999'
 'CAMP10000']

CHANNEL
['Search', 'Email', 'Influencer', 'Social', 'Display']
Categories (5, object): ['Display', 'Email', 'Influencer', 'Search', 'Social']
channel
Display       2069
Influencer    2056
Email         1996
Social        1955
Search        1924
Name: count, dtype: int64
channel
Display       2069
Influencer    2056
Email         1996
Social        1955
Search        1924
Name: count, dtype: int64

## Standardization of Categorical Variables

Categorical variables were reviewed to identify inconsistent naming conventions that could affect aggregation and reporting.

The `channel` column was inspected for variations in capitalization, spacing, and formatting.

After inspection, category labels were standardized where necessary to ensure that each marketing channel was represented consistently throughout the analysis.

The `campaignid` column was retained without modification, as each value serves as a unique campaign identifier.

In [14]:
df.to_csv("clean_campaign_data.csv", index=False)

## Exporting the Clean Dataset

After completing all data quality checks, the cleaned dataset was exported as `clean_campaign_data.csv`.

This processed dataset serves as the single source of truth for all subsequent analyses, including exploratory data analysis, SQL-based marketing analytics, feature engineering, and Power BI dashboard development.

Maintaining a separate processed dataset improves reproducibility by preserving the original raw data while ensuring that downstream analyses use a validated and consistent version of the data.

End of notebook.